baseURL = '/'
languageCode = 'en-us'
title = 'Free is cool ğŸ˜'
defaultContentLanguage = 'zh-tw'
theme = 'FixIt'
description = 'è’é›†ç¶²è·¯å…è²»ç°¡å–®å¥½ç”¨è³‡è¨Š'
keywords = ['free', 'easy', 'å…è²»', 'ç°¡å–®']
defaultTheme = 'auto'
disableThemeInject = false
externalIcon = true

[params.author]
  name = 'Administrator'

[params.app]
  svgFavicon = 'https://fixit.lruihao.cn/images/hugo.min.svg'

[params.header.title]
  typeit = true

[params.footer]
  author = false
  copyright = false

[params.githubCorner]
  enable = true
  permalink = 'https://github.com/tw1720'
  title = 'My GitHub'
  position = 'right'

[params.backToTop]
  scrollpercent = true

[params.pace]
  enable = true
  color = 'pink'

[params.page]
  wordCount = false
  readingTime = false
  license = ''

[params.page.share]
  enable = false

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'tokyonight-day'
    tabWidth = 2

[menu]
  [[menu.main]]
    identifier = 'About'
    name = 'About'
    url = '/about'
