baseURL = 'https://free.is-cool.dev/'
title = 'Free is cool ğŸ˜ '
languageCode = 'zh-tw'
defaultContentLanguage = 'zh-tw'
theme = 'FixIt'
keywords = ['free', 'cool', 'easy', 'å…è²»', 'å¾ˆé…·', 'ç°¡å–®', 'å¥½ç”¨']
defaultTheme = 'auto'
disableThemeInject = false
externalIcon = true

[params]
  description = 'å…è²»å¾ˆé…·!è’é›†ç¶²è·¯å…è²»ç°¡å–®å¥½ç”¨è³‡è¨Š,ç°¡å–®ä¹¾æ·¨çš„ç‰ˆé¢,ä¸ç”¨å¾ˆå°ˆæ¥­'

[params.author]
  name = 'Admin'

[params.app]
  svgFavicon = 'https://free.is-cool.dev/favicon.ico'

[params.header.title]
  typeit = true

[params.footer]
  author = false
  copyright = false

[params.githubCorner]
  enable = true
  permalink = 'https://github.com/tw1720'
  title = 'My GitHub'
  position = 'right'

[params.backToTop]
  scrollpercent = true

[params.pace]
  enable = true
  color = 'pink'

[params.page]
  wordCount = false
  readingTime = false
  license = ''

[params.page.share]
  enable = false

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'tokyonight-day'
    tabWidth = 2

[menu]
  [[menu.main]]
    name = 'Free'
    url = '/categories/free/'
    pre = '<i class="fa-solid fa-tag"></i>'
    weight = 1
  [[menu.main]]
    name = 'Note'
    url = '/categories/note/'
    pre = '<i class="fa-solid fa-book"></i>'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = '/about'
    pre = '<i class="fa-solid fa-circle-info"></i>'
    weight = 3